version: 2
updates:

# Config for AMP plugin.
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "17:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  groups:
    code-quality:
      patterns:
        - "phpstan/*"
        - "szepeviktor/phpstan-wordpress"
        - "phpcompatibility/php-compatibility"
        - "slevomat/coding-standard"
        - "dealerdirect/phpcodesniffer-composer-installer"
        - "squizlabs/php_codesniffer"
        - "wp-coding-standards/wpcs"
        - "wp-phpunit/wp-phpunit"
        - "yoast/phpunit-polyfills"

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "17:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  groups:
    wordpress-packages:
      patterns:
        - "@wordpress/*"
    plugin-cli:
      patterns:
        - "@octokit/rest"
        - "commander"
        - "fs-extra"
        - "fast-glob"
        - "lodash"
    code-quality:
      patterns:
        - "husky"
        - "lint-staged"
  ignore:
  # Latest version of chalk is pure ESM.
  - dependency-name: chalk

# Config for GitHub Actions.
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "17:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  groups:
    github-actions:
      patterns:
        - "actions/*"
