name: Setup Node.js and npm

description: Setup Node.js and npm with caching

runs:
  using: 'composite'
  steps:
    - name: Configure Node.js cache
      uses: actions/cache@v3.3.2
      id: node-npm-cache
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package*.json') }}-${{ hashFiles('.github/actions/setup-node-npm/action.yml') }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install NodeJS dependencies
      if: ${{ steps.node-npm-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: npm ci
