---
name: Deploy to WordPress.org

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release Performance Lab Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: WordPress plugin deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: true
        env:
          SVN_PASSWORD: 'user'
          SVN_USERNAME: 'pass'
          SLUG: performance-lab

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.workspace}}/${{ github.event.repository.name }}.zip
